### ISSUE TITLE
[1.18.2] using broom: logout

### ISSUE THREAD

**Issue by MSandro** [BloomhouseMC/Bewitchment-Plus#9]
if I press W on the any Broom, it logs me out! (Single and Multi Player)
![image](https://user-images.githubusercontent.com/10937159/182395609-08f57180-cd91-43f8-80b3-a8db831f46d2.png)
Fabric API 0.14.8
Fabric loader 0.58.0
Bewitchment 1.18-23
BewitchmentPlus 1.17.2-17
```
[16:00:28] [Netty Server IO #1/ERROR]: Exception occurred in netty pipeline
java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 1, cap: 256))
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.readBoolean(AbstractByteBuf.java:739) ~[netty-all-4.1.68.Final.jar:?]
	at net.minecraft.network.PacketByteBuf.readBoolean(PacketByteBuf:1008) ~[?:?]
	at moriyashiine.bewitchment.common.network.packet.TogglePressingForwardPacket.handle(TogglePressingForwardPacket.java:30) ~[bewitchment-1.18-23.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:89) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-4536c950854534c8.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:38) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-4536c950854534c8.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:100) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-4536c950854534c8.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.handle(ServerPlayNetworkAddon.java:84) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-4536c950854534c8.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.handler$ell000$handleCustomPayloadReceivedAsync(ServerPlayNetworkHandler:2214) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.onCustomPayload(ServerPlayNetworkHandler) ~[?:?]
	at net.minecraft.network.packet.c2s.play.CustomPayloadC2SPacket.apply(CustomPayloadC2SPacket:38) ~[?:?]
	at net.minecraft.network.packet.c2s.play.CustomPayloadC2SPacket.apply(CustomPayloadC2SPacket:7) ~[?:?]
	at net.minecraft.network.ClientConnection.handlePacket(ClientConnection:172) ~[?:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection:157) ~[?:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection:55) ~[?:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

I have added the mod to my Modpack Sky FABRICation 3.
and I did not build a Altar so I tried it without ME.

**Comment by venny-ven** [comment]
Seconding this. Fabric 1.18.2. Only mods present are latest release versions of Bewitchment, Bewitchment Plus, and their dependencies: Fabric API, Cloth Config, GeckoLib, Patchouli, Pehkui, Trinkets.

To reproduce: create a new world in creative, grab any broom, enter survival, sit down on the broom, and attempt to fly.

**Comment by Bob74** [comment]
@MSandro @neilkirklin 
This is an issue with Bewitchment (https://github.com/MoriyaShiine/bewitchment/issues/314).
It crashes because you have 0 ME, I have forked Bewitchment code and fixed it in this version: https://github.com/Bob74/bewitchment/releases/tag/1.18.2-24
